import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HMS Dashboard",
  description: "HMS management dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*
          Runtime env config: `/env-config.js` is generated by entrypoint.sh
          at container start from the k8s ConfigMap. `beforeInteractive`
          ensures window.__ENV__ is populated before any React code runs.
        */}
        <Script src="/env-config.js" strategy="beforeInteractive" />
        {children}
      </body>
    </html>
  );
}
