import React from 'react'
import { render } from '@testing-library/react'
import RootLayout from '../../src/app/layout'

describe('RootLayout Component', () => {
  it('should render html and body elements', () => {
    const { container } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )

    const html = container.querySelector('html')
    const body = container.querySelector('body')

    expect(html).toBeInTheDocument()
    expect(body).toBeInTheDocument()
  })

  it('should set lang attribute to en', () => {
    const { container } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )

    const html = container.querySelector('html')
    expect(html).toHaveAttribute('lang', 'en')
  })

  it('should render children content', () => {
    const { getByText } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )

    expect(getByText('Test Content')).toBeInTheDocument()
  })

  it('should apply Inter font class to body', () => {
    const { container } = render(
      <RootLayout>
        <div>Test Content</div>
      </RootLayout>
    )

    const body = container.querySelector('body')
    expect(body.className).toBeTruthy()
  })

  it('should export metadata', () => {
    expect(RootLayout.metadata).toBeDefined()
    expect(RootLayout.metadata.title).toBe('Create Next App')
    expect(RootLayout.metadata.description).toBe('Generated by create next app')
  })
})
